#!/bin/sh
# Start & stop mediatomb server

PIDFILE=/var/run/mediatomb.pid
DAEMON=mediatomb

case "$1" in
start)
if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
echo "mediatomb already running."
exit 0
fi
echo -n "Starting mediatomb..."
$DAEMON -m /wymedia > /wymedia/usr/var/log/mediatomb.log 2>&1 &
echo $! > $PIDFILE
echo ok
;;
stop)
if [ ! -s $PIDFILE ]; then
echo "mediatomb not running."
exit 0
fi
echo -n "Stopping mediatomb..."
kill $(cat $PIDFILE) >/dev/null 2>&1
rm -f $PIDFILE
echo ok
;;
restart)
$0 stop
$0 start
;;
status)
if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
echo "mediatomb running"
else
echo "mediatomb not running"
exit 1
fi
exit 0
;;
*)
echo "Usage: $0 {start|stop|restart|status}"
exit 1
;;
esac

exit 0
